- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Atlas
  - Amber
  - Bagel
  - Box
  - Cluster
  - Cog
  - Core
  - Fland
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Origin
  - Saltern
  - Packed
  - Reach
  - FlandHighPop
  - OasisHighPop
  - Train
  - Barratry # Goobstation - Re-add barratry
  - Kettle # Goobstation - Re-add kettle (before it was gemini!)
  - Gamma # Gabystation
  - Gax # Gabystation
  - Falcon #Gabystation
